import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ms';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.fireworks': 'Fireworks & Sparklers',
    'nav.packages': 'Event Packages',
    'nav.permitGuide': 'Permit Guide',
    'nav.safetyGuide': 'Safety Tips',
    'nav.testimonials': 'Reviews',
    'nav.contact': 'Contact Us',
    
    // Homepage
    'home.hero.title': '🏆 Distributor Mercun Berlesen Rasmi #1 Malaysia',
    'home.hero.subtitle': '100% Legal & Certified • Premium Quality • Professional Service',
    'home.hero.description': 'MercunBerlesen - Distributor mercun berlesen rasmi Malaysia. Semua produk 100% legal, berkualiti premium dengan dokumentasi lengkap. Khidmat profesional untuk event korporat dan majlis peribadi.',
    'home.hero.viewFireworks': '🔥 View All Fireworks!',
    'home.section.title': 'Nak Sambut Berlesen Macam Mana Tahun Ni?',
    'home.section.description': 'Balik kampung ke, open house ke, kenduri raya ke - MercunBerlesen ada semua! Pakej lengkap dengan panduan permit. Marilah beraya dengan meriah!',
    'home.card.fireworks.title': '🎇 Koleksi Mercun Berlesen Terlengkap',
    'home.card.fireworks.description': 'Lebih 100 jenis mercun untuk sambutan Berlesen! Bunga api murah dari RM10, mercun premium hingga RM1000+. Dari yang selamat budak-budak sampai yang power maksima untuk beraya!',
    'home.card.packages.title': '📦 Pakej Berlesen Siap Sedia',
    'home.card.packages.description': 'Malas nak pilih satu-satu? Ambil pakej Berlesen kami sahaja! Pakej balik kampung, open house, kenduri - semua lengkap. Senang je!',
    'home.card.permit.title': '📄 Panduan Permit Berlesen PDRM',
    'home.card.permit.description': 'Tak tahu macam mana nak mohon permit untuk sambutan Berlesen? Rilek je! Kami ajar step by step sampai dapat permit. Guidance percuma untuk pelanggan MercunBerlesen!',
    'home.why.title': 'Why Choose Us?',
    'home.why.licensed': '✅ Properly Licensed',
    'home.why.licensed.desc': 'MercunBerlesen ada lesen sah kerajaan - bukan kedai haram! Semua produk Berlesen diluluskan & selamat untuk sambutan',
    'home.why.products': '💥 Koleksi Berlesen Terbanyak',
    'home.why.products.desc': 'Koleksi mercun Berlesen terbesar di Malaysia! 8 kategori dari bunga api sampai letupan besar. Mesti ada yang sesuai untuk Berlesen anda!',
    'home.why.permit': '📋 Bantuan Permit Berlesen',
    'home.why.permit.desc': 'Tak nak susah-susah uruskan permit untuk Berlesen? Kami guide sampai dapat permit. WhatsApp MercunBerlesen je!',
    'home.why.support': '💬 Khidmat Pelanggan Berlesen',
    'home.why.support.desc': 'Ada soalan tentang mercun Berlesen? WhatsApp terus! Balas pantas. Khidmat pelanggan terbaik untuk sambutan Berlesen!',
    
    // Products
    'products.title': 'Semua Mercun Berlesen Ada Di Sini!',
    'products.description': 'Koleksi lengkap 100+ jenis mercun & bunga api untuk Berlesen! Harga dari RM10 sahaja! Pilih mengikut kategori atau cari yang anda nak untuk sambutan Berlesen. Semua sah & berkualiti!',
    'products.search.placeholder': 'Cari mercun Berlesen yang anda mahu?',
    'products.category.all': 'All',
    'products.category.premium': '🇲🇾 Mercun Berlesen Special',
    'products.category.sparkle': '✨ Bunga Api Berlesen - Budak Suka!',
    'products.category.kidsFirecrackers': '👶 Mercun Selamat Berlesen Budak',
    'products.category.poppop': '🎪 Pop-Pop Meriah Berlesen',
    'products.category.fountainBlast': '⛲ Pancutan Berlesen Hebat',
    'products.category.oneshot': '💥 Letupan Berlesen Besar!',
    'products.category.rocket': '🚀 Roket Berlesen Terbang Tinggi',
    'products.category.reddragon': '🐉 Naga Merah Berlesen Power',
    'products.noResults': 'Alamak! Tiada mercun Berlesen yang sepadan dengan carian anda. Cuba cari yang lain untuk sambutan Berlesen.',
    'products.addToCart': '🛒 Add to Cart',
    'products.watchVideo': '📹 Watch Video',
    
    // Safety Guide
    'safety.hero.title': 'Beraya Selamat! Keselamatan Dahulu!',
    'safety.hero.subtitle': 'Mercun Berlesen memang hebat tapi kena guna betul-betul. Jangan sampai Berlesen rosak sebab tak ikut safety!',
    'safety.warning.title': '⚠️ Serious Warning!',
    'safety.warning.description': 'Mercun Berlesen boleh bahaya kalau main sesuka hati. Ikut peraturan keselamatan - sambutan Berlesen kena selamat dan meriah!',
    'safety.tips.title': 'Safety Tips You Must Know',
    'safety.tip1.title': '👨‍👩‍👧‍👦 Must Have Adult Supervision',
    'safety.tip1.desc': 'Budak-budak jangan main mercun Berlesen bersendirian! Mesti ada orang dewasa jaga. Berlesen selamat, Berlesen meriah!',
    'safety.tip2.title': '👓 Protect Your Eyes!',
    'safety.tip2.desc': 'Pakai cermin mata keselamatan waktu beraya. Mata cuma satu pasang, rosak tak boleh tukar macam telefon. Jaga betul-betul untuk Berlesen yang selamat!',
    'safety.tip3.title': '🏃‍♂️ Keep Others Away',
    'safety.tip3.desc': 'Suruh tetamu Berlesen berdiri jauh 8-10 meter. Jangan sesak-sesak masa beraya dengan mercun!',
    'safety.tip4.title': '🚿 Water Ready on Standby',
    'safety.tip4.desc': 'Sediakan air atau pemadam api masa beraya dengan mercun. Kalau ada kecemasan, boleh padam cepat-cepat! Berlesen selamat, hati tenang!',
    'safety.steps.title': 'Step-by-Step Guide to Follow',
    'safety.before.title': '📋 Before Using Fireworks',
    'safety.before.step1': 'Read instructions carefully first',
    'safety.before.step2': 'Periksa cuaca - kalau angin kuat jangan main mercun Berlesen',
    'safety.before.step3': 'Have water bucket or hose on standby',
    'safety.before.step4': 'Clear area of flammable materials',
    'safety.before.step5': 'Have adult supervisor who knows what they\'re doing',
    'safety.during.title': '🔥 During Use',
    'safety.during.step1': 'Light only one firework at a time',
    'safety.during.step2': 'Use long lighter or punk stick',
    'safety.during.step3': 'After lighting, run away quickly',
    'safety.during.step4': 'If it doesn\'t go off, don\'t try again!',
    'safety.during.step5': 'Kucing anjing masuk rumah masa beraya dengan mercun',
    'safety.after.title': '🧹 After Party Cleanup',
    'safety.after.step1': 'Wait 20 minutes before cleanup',
    'safety.after.step2': 'Soak all firework casings in water',
    'safety.after.step3': 'Dispose properly in trash bin',
    'safety.emergency.title': '🚨 Emergency? Call Quickly!',
    'safety.emergency.description': 'If anything happens, call emergency immediately! Don\'t delay!',
    'safety.emergency.numbers': 'Emergency Numbers',
    'safety.emergency.fire': '🚒 Fire Department: 994',
    'safety.emergency.police': '👮‍♂️ Police: 999',
    'safety.emergency.ambulance': '🚑 Ambulance: 999',

    // Permit Guide
    'permit.hero.title': '🏛️ Nak Mohon Permit Berlesen PDRM? Senang Je!',
    'permit.hero.subtitle': 'Panduan step by step macam mana nak dapat permit mercun untuk sambutan Berlesen. Ikut je, dijamin lulus!',
    'permit.requirements.title': '📋 Things You Need to Have',
    'permit.requirements.step1': '🆔 IC & passport size photo',
    'permit.requirements.step2': '📄 Permission letter from MPKB/MB/MP',
    'permit.requirements.step3': '🗺️ Pelan lokasi sambutan Berlesen (lakaran pun boleh)',
    'permit.requirements.step4': '🛡️ Perlindungan insurans (untuk majlis Berlesen besar)',
    'permit.process.title': '🚶‍♂️ Step By Step Process',
    'permit.process.step1': 'Go to the nearest police station',
    'permit.process.step2': 'Fill application form (they have it)',
    'permit.process.step3': 'Submit all documents together',
    'permit.process.step4': 'Pay fee (usually around RM50-100)',
    'permit.process.step5': 'Wait for approval 3-7 working days',
    'permit.tips.title': '💡 Pro Tips From Us',
    'permit.tips.tip1': 'Apply early, don\'t stress at the last minute',
    'permit.tips.tip2': 'Make sure all documents are complete',
    'permit.tips.tip3': 'Beli mercun Berlesen dari MercunBerlesen - kedai berlesen sahaja',
    'permit.tips.tip4': 'Follow safety guidelines strictly',
    'permit.help.title': '🤝 We Can Help!',
    'permit.help.description': 'Keliru dengan proses permit Berlesen? WhatsApp MercunBerlesen! Kami bimbing percuma sampai dapat permit untuk sambutan Berlesen.',

    // Contact
    'contact.hero.title': '💬 Selamat Hari Berlesen! Ada Soalan? WhatsApp Je!',
    'contact.hero.subtitle': 'Khidmat pelanggan MercunBerlesen balas pantas. Soalan pasal mercun Berlesen, permit, delivery - semua boleh tanya! Marilah beraya dengan meriah!',
    'contact.whatsapp.title': '📱 WhatsApp Us Now',
    'contact.whatsapp.description': 'Fastest way to contact us! Reply within 5 minutes (business hours)',
    'contact.whatsapp.number': '+60 13-734 0415',
    'contact.whatsapp.button': '💬 Chat on WhatsApp',
    'contact.email.title': '📧 Email Us',
    'contact.email.description': 'For business inquiries or bulk orders for Berlesen',
    'contact.email.address': 'hello@mercunberlesen.com',
    'contact.hours.title': '🕐 Business Hours',
    'contact.hours.weekdays': 'Monday - Friday: 9AM - 6PM',
    'contact.hours.saturday': 'Saturday: 9AM - 2PM',
    'contact.hours.sunday': 'Sunday: Closed (but WhatsApp still active!)',
    'contact.location.title': '📍 Pickup Location',
    'contact.location.address': 'Klang Valley area (exact location via WhatsApp)',

    // Cart
    'cart.title': '🛒 Troli Berlesen Anda',
    'cart.empty': 'Alamak! Troli kosong. Nak beli mercun Berlesen dahulu?',
    'cart.empty.button': '🔥 Beli Mercun Berlesen',
    'cart.item.remove': 'Remove',
    'cart.item.quantity': 'Quantity',
    'cart.subtotal': 'Subtotal',
    'cart.delivery': 'Delivery Fee',
    'cart.total': 'Total Payment',
    'cart.checkout': '💳 Checkout Now',
    'cart.continue': '🛍️ Continue Shopping',
    'cart.delivery.note': '🚚 Penghantaran percuma untuk pesanan Berlesen RM200+! Hantar sampai kampung!',
    'cart.update': 'Update',
    'cart.clear': 'Clear Cart',

    // Packages
    'packages.hero.title': '📦 Pakej Berlesen Siap Sedia Terbaik!',
    'packages.hero.subtitle': 'Malas nak pilih satu-satu? Kami dah pilih kombinasi terbaik untuk sambutan Berlesen anda!',
    'packages.wedding.title': '💒 Pakej Kahwin Beraya',
    'packages.wedding.description': 'Pakej istimewa untuk majlis perkahwinan masa musim Berlesen! Termasuk pancutan, bunga api, dan letupan finale!',
    'packages.wedding.price': 'Dari RM299',
    'packages.raya.title': '🌙 Pakej Berlesen Tradisional',
    'packages.raya.description': 'Sambutan Hari Berlesen memang kena ada mercun! Pakej lengkap dengan kegemaran tradisional untuk beraya meriah.',
    'packages.raya.price': 'Dari RM199',
    'packages.birthday.title': '🎂 Pakej Hari Jadi Berlesen',
    'packages.birthday.description': 'Hari jadi dalam bulan Berlesen kena sambut double meriah! Ada pilihan selamat untuk budak-budak.',
    'packages.birthday.price': 'Dari RM149',
    'packages.newyear.title': '🎊 Pakej Tahun Baru Berlesen',
    'packages.newyear.description': 'Sambut tahun baru dengan semangat Berlesen! Sempurna untuk parti countdown beraya.',
    'packages.newyear.price': 'Dari RM399',
    'packages.custom.title': '🎨 Pakej Berlesen Khas',
    'packages.custom.description': 'Nak sambutan Berlesen yang istimewa? Beritahu budget & keperluan, MercunBerlesen buatkan pakej khas untuk anda!',
    'packages.custom.button': '💬 Minta Pakej Berlesen Khas',
    'packages.whatsIncluded': 'What\'s Included in Package:',
    'packages.orderNow': '🛒 Order Now',

    // Testimonials
    'testimonials.hero.title': '🌟 Apa Kata Pelanggan MercunBerlesen?',
    'testimonials.hero.subtitle': 'Ulasan sebenar dari pelanggan yang beraya dengan mercun kami! Tengok sendiri kenapa mereka suka sambut Berlesen dengan MercunBerlesen!',
    'testimonials.review1.name': 'Ahmad from KL',
    'testimonials.review1.text': 'Memang terbaik untuk beraya! Pesan untuk majlis kahwin masa Berlesen, hantar tepat masa, mercun hebat habis. Tetamu semua gembira beraya!',
    'testimonials.review1.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review2.name': 'Siti from JB',
    'testimonials.review2.text': 'Kali pertama beli mercun Berlesen online, bimbang jugak. Tapi kualiti memang top, khidmat pelanggan pun terbaik untuk musim Berlesen!',
    'testimonials.review2.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review3.name': 'Robert from Penang',
    'testimonials.review3.text': 'Dah 3 tahun beraya dengan mercun MercunBerlesen. Kualiti konsisten, harga berpatutan. Sangat recommend untuk sambutan Berlesen!',
    'testimonials.review3.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review4.name': 'Fatimah from Shah Alam',
    'testimonials.review4.text': 'Pakej Berlesen yang kami pesan memang berbaloi! Jiran semua tanya beli kat mana sebab beraya meriah sangat. Pasti pelanggan tetap MercunBerlesen!',
    'testimonials.review4.rating': '⭐⭐⭐⭐⭐',
    'testimonials.cta.title': 'Nak Beraya Meriah Macam Mereka?',
    'testimonials.cta.button': '🛒 Start Shopping',

    // Footer
    'footer.description': 'MercunBerlesen - kedai mercun Hari Berlesen terbaik Malaysia! Harga murah, kualiti hebat, hantar ke seluruh negara. Berlesen & sah. Selamat Hari Berlesen!',
    'footer.quickLinks': 'Quick Links',
    'footer.categories': 'Kategori Popular',
    'footer.support': 'Customer Support',
    'footer.whatsapp': '💬 WhatsApp Us',
    'footer.email': '📧 Email Us', 
    'footer.hours': '🕐 Business Hours',
    'footer.hours.time': '9AM - 6PM (Monday-Saturday)',
    'footer.legal': 'Legal Info',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.license': 'Licensed by Malaysian Govt',
    'footer.copyright': '© 2025 MercunBerlesen. Selamat Hari Berlesen! All rights reserved.',

    // Common
    'whatsapp.text': '💬 Tekan sini untuk WhatsApp MercunBerlesen',
    'common.price': 'RM',
    'common.products': 'products',
    'common.loading': 'Loading...',
    'common.error': 'Oops! There\'s an error. Try again.',
    'common.success': 'Success! Thank you!',
  },
  
  ms: {
    // Navigation
    'nav.home': 'Utama',
    'nav.fireworks': 'Mercun & Bunga Api',
    'nav.packages': 'Pakej Berlesen',
    'nav.permitGuide': 'Panduan Permit',
    'nav.safetyGuide': 'Tips Keselamatan',
    'nav.testimonials': 'Ulasan',
    'nav.contact': 'Hubungi Kami',
    
    // Homepage
    'home.hero.title': '🏆 Distributor Mercun Berlesen Rasmi #1 Malaysia',
    'home.hero.subtitle': '100% Legal & Berlesen • Kualiti Premium • Khidmat Profesional',
    'home.hero.description': 'MercunBerlesen - Distributor mercun berlesen rasmi Malaysia. Semua produk 100% sah, berkualiti premium dengan dokumentasi lengkap. Khidmat profesional untuk acara korporat dan majlis peribadi.',
    'home.hero.viewFireworks': '🔥 Tengok Koleksi Berlesen!',
    'home.section.title': 'Nak Sambut Berlesen Macam Mana Tahun Ni?',
    'home.section.description': 'Balik kampung ke, open house ke, kenduri Berlesen ke - MercunBerlesen ada semua! Pakej lengkap dengan panduan permit. Beraya dengan meriah!',
    'home.card.fireworks.title': '🎇 Koleksi Mercun Berlesen Terlengkap',
    'home.card.fireworks.description': 'Lebih 100 jenis mercun untuk sambutan Berlesen! Harga dari RM10 sampai RM1000+. Dari yang selamat budak-budak sampai yang power maksima untuk beraya!',
    'home.card.packages.title': '📦 Pakej Berlesen Siap Sedia',
    'home.card.packages.description': 'Malas nak pilih satu-satu? Ambil pakej Berlesen kami sahaja! Balik kampung, open house, kenduri - semua lengkap. Senang je!',
    'home.card.permit.title': '📄 Panduan Permit Berlesen PDRM',
    'home.card.permit.description': 'Tak tahu macam mana nak mohon permit untuk sambutan Berlesen? Rilek je! Kami ajar step by step sampai dapat permit untuk beraya!',
    'home.why.title': 'Kenapa Pilih Kami?',
    'home.why.licensed': '✅ Berlesen Sah',
    'home.why.licensed.desc': 'MercunBerlesen ada lesen sah kerajaan - bukan kedai haram! Semua produk Berlesen diluluskan & selamat untuk sambutan.',
    'home.why.products': '💥 Koleksi Berlesen Terbanyak',
    'home.why.products.desc': 'Koleksi mercun Berlesen terbesar di Malaysia! 8 kategori dari bunga api sampai letupan besar. Mesti ada yang sesuai untuk Berlesen anda!',
    'home.why.permit': '📋 Bantuan Permit Berlesen',
    'home.why.permit.desc': 'Tak nak susah-susah uruskan permit untuk Berlesen? Kami guide sampai dapat permit. WhatsApp MercunBerlesen je!',
    'home.why.support': '💬 Khidmat Pelanggan Berlesen',
    'home.why.support.desc': 'Ada soalan tentang mercun Berlesen? WhatsApp terus! Balas pantas. Khidmat pelanggan terbaik untuk sambutan Berlesen!',
    
    // Products
    'products.title': 'Semua Mercun Berlesen Ada Di Sini!',
    'products.description': 'Koleksi lengkap 100+ jenis mercun & bunga api untuk sambutan Berlesen! Harga dari RM10 sahaja! Pilih mengikut kategori atau cari yang anda nak untuk beraya. Semua sah & berkualiti untuk Berlesen meriah!',
    'products.search.placeholder': 'Cari mercun Berlesen yang anda mahu?',
    'products.category.all': 'Semua',
    'products.category.premium': '🇲🇾 Mercun Berlesen Special',
    'products.category.sparkle': '✨ Bunga Api Berlesen - Budak Suka!',
    'products.category.kidsFirecrackers': '👶 Mercun Selamat Berlesen Budak',
    'products.category.poppop': '🎪 Pop-Pop Meriah Berlesen',
    'products.category.fountainBlast': '⛲ Pancutan Berlesen Hebat',
    'products.category.oneshot': '💥 Letupan Berlesen Besar!',
    'products.category.rocket': '🚀 Roket Berlesen Terbang Tinggi',
    'products.category.reddragon': '🐉 Naga Merah Berlesen Power',
    'products.noResults': 'Alamak! Tiada mercun Berlesen yang sepadan dengan carian anda. Cuba cari yang lain untuk sambutan Berlesen.',
    'products.addToCart': '🛒 Masuk Troli',
    'products.watchVideo': '📹 Tengok Video',
    
    // Safety Guide
    'safety.hero.title': 'Beraya Selamat! Keselamatan Dahulu!',
    'safety.hero.subtitle': 'Mercun Berlesen memang hebat tapi kena guna betul-betul. Jangan sampai Berlesen rosak sebab tak ikut safety!',
    'safety.warning.title': '⚠️ Amaran Serius!',
    'safety.warning.description': 'Mercun Berlesen boleh bahaya kalau main sesuka hati. Ikut peraturan keselamatan - sambutan Berlesen kena selamat dan meriah!',
    'safety.tips.title': 'Tips Keselamatan Yang Mesti Tahu',
    'safety.tip1.title': '👨‍👩‍👧‍👦 Mesti Ada Dewasa',
    'safety.tip1.desc': 'Budak-budak jangan main mercun Berlesen bersendirian! Mesti ada orang dewasa jaga. Berlesen selamat, Berlesen meriah!',
    'safety.tip2.title': '👓 Jaga Mata!',
    'safety.tip2.desc': 'Pakai cermin mata keselamatan waktu beraya. Mata cuma satu pasang, rosak tak boleh tukar macam telefon. Jaga betul-betul untuk Berlesen yang selamat!',
    'safety.tip3.title': '🏃‍♂️ Orang Jauh Sikit',
    'safety.tip3.desc': 'Suruh tetamu Berlesen berdiri jauh 8-10 meter. Jangan sesak-sesak masa beraya dengan mercun!',
    'safety.tip4.title': '🚿 Air Sedia Siaga',
    'safety.tip4.desc': 'Sediakan air atau pemadam api masa beraya dengan mercun. Kalau ada kecemasan, boleh padam cepat-cepat! Berlesen selamat, hati tenang!',
    'safety.steps.title': 'Panduan Langkah Demi Langkah',
    'safety.before.title': '📋 Sebelum Main Mercun',
    'safety.before.step1': 'Baca arahan betul-betul dahulu',
    'safety.before.step2': 'Periksa cuaca - kalau angin kuat jangan main mercun Berlesen',
    'safety.before.step3': 'Sediakan baldi air atau hos siaga',
    'safety.before.step4': 'Bersihkan kawasan dari barang mudah terbakar',
    'safety.before.step5': 'Ada penyelia dewasa yang tahu apa yang dibuat',
    'safety.during.title': '🔥 Masa Tengah Main',
    'safety.during.step1': 'Nyalakan satu mercun sahaja pada satu masa',
    'safety.during.step2': 'Guna pemetik api panjang atau batang penyala',
    'safety.during.step3': 'Lepas nyalakan, lari jauh cepat-cepat',
    'safety.during.step4': 'Kalau tak meletup, jangan cuba lagi!',
    'safety.during.step5': 'Kucing anjing masuk rumah masa beraya dengan mercun',
    'safety.after.title': '🧹 Pembersihan Selepas Parti',
    'safety.after.step1': 'Tunggu 20 minit baru nak bersihkan',
    'safety.after.step2': 'Rendam semua bekas mercun dalam air',
    'safety.after.step3': 'Buang betul-betul dalam tong sampah',
    'safety.emergency.title': '🚨 Kecemasan? Panggil Cepat!',
    'safety.emergency.description': 'Kalau ada apa-apa berlaku, panggil kecemasan terus! Jangan tangguh!',
    'safety.emergency.numbers': 'Nombor Kecemasan',
    'safety.emergency.fire': '🚒 Bomba: 994',
    'safety.emergency.police': '👮‍♂️ Polis: 999',
    'safety.emergency.ambulance': '🚑 Ambulans: 999',

    // Permit Guide
    'permit.hero.title': '🏛️ Nak Mohon Permit Berlesen PDRM? Senang Je!',
    'permit.hero.subtitle': 'Panduan step by step macam mana nak dapat permit mercun untuk sambutan Berlesen. Ikut je, dijamin lulus!',
    'permit.requirements.title': '📋 Benda-Benda Yang Perlu Ada',
    'permit.requirements.step1': '🆔 KP & gambar saiz pasport',
    'permit.requirements.step2': '📄 Surat kebenaran MPKB/MB/MP',
    'permit.requirements.step3': '🗺️ Pelan lokasi sambutan Berlesen (lakaran pun boleh)',
    'permit.requirements.step4': '🛡️ Perlindungan insurans (untuk majlis Berlesen besar)',
    'permit.process.title': '🚶‍♂️ Proses Langkah Demi Langkah',
    'permit.process.step1': 'Pergi balai polis yang terdekat',
    'permit.process.step2': 'Isi borang permohonan (mereka ada)',
    'permit.process.step3': 'Hantar dokumen semua sekali',
    'permit.process.step4': 'Bayar yuran (biasanya sekitar RM50-100)',
    'permit.process.step5': 'Tunggu kelulusan 3-7 hari bekerja',
    'permit.tips.title': '💡 Tips Profesional Dari Kami',
    'permit.tips.tip1': 'Mohon awal-awal, jangan saat akhir',
    'permit.tips.tip2': 'Pastikan dokumen semua lengkap',
    'permit.tips.tip3': 'Beli mercun Berlesen dari MercunBerlesen - kedai berlesen sahaja',
    'permit.tips.tip4': 'Ikut garis panduan keselamatan ketat-ketat',
    'permit.help.title': '🤝 Kami Boleh Tolong!',
    'permit.help.description': 'Keliru dengan proses permit Berlesen? WhatsApp MercunBerlesen! Kami bimbing percuma sampai dapat permit untuk sambutan Berlesen.',

    // Contact
    'contact.hero.title': '💬 Selamat Hari Berlesen! Ada Soalan? WhatsApp Je!',
    'contact.hero.subtitle': 'Khidmat pelanggan MercunBerlesen balas pantas. Soalan pasal mercun Berlesen, permit, delivery - semua boleh tanya! Marilah beraya dengan meriah!',
    'contact.whatsapp.title': '📱 Hubungi Kami Sekarang',
    'contact.whatsapp.description': 'Cara terpantas nak hubungi MercunBerlesen! Balas dalam 5 minit untuk soalan Berlesen (waktu perniagaan)',
    'contact.whatsapp.number': '+60 13-734 0415',
    'contact.whatsapp.button': '💬 Sembang Sekarang',
    'contact.email.title': '📧 Emel Kami',
    'contact.email.description': 'Untuk pertanyaan perniagaan atau pesanan pukal untuk Berlesen',
    'contact.email.address': 'hello@mercunberlesen.com',
    'contact.hours.title': '🕐 Waktu Perniagaan',
    'contact.hours.weekdays': 'Isnin - Jumaat: 9 PAGI - 6 PETANG',
    'contact.hours.saturday': 'Sabtu: 9 PAGI - 2 PETANG',
    'contact.hours.sunday': 'Ahad: Tutup (tapi masih boleh hubungi!)',
    'contact.location.title': '📍 Lokasi Ambilan',
    'contact.location.address': 'Kawasan Klang Valley (lokasi tepat melalui pesanan)',

    // Cart
    'cart.title': '🛒 Troli Berlesen Anda',
    'cart.empty': 'Alamak! Troli kosong. Nak beli mercun Berlesen dahulu?',
    'cart.empty.button': '🔥 Beli Mercun Berlesen',
    'cart.item.remove': 'Buang',
    'cart.item.quantity': 'Kuantiti',
    'cart.subtotal': 'Jumlah Kecil',
    'cart.delivery': 'Yuran Penghantaran',
    'cart.total': 'Jumlah Bayar',
    'cart.checkout': '💳 Bayar Sekarang',
    'cart.continue': '🛍️ Teruskan Beli-Belah',
    'cart.delivery.note': '🚚 Penghantaran percuma untuk pesanan Berlesen RM200+! Hantar sampai kampung!',
    'cart.update': 'Kemas Kini',
    'cart.clear': 'Kosongkan Troli',

    // Packages
    'packages.hero.title': '📦 Pakej Berlesen Siap Sedia Terbaik!',
    'packages.hero.subtitle': 'Malas nak pilih satu-satu? Kami dah pilih kombinasi terbaik untuk sambutan Berlesen anda!',
    'packages.wedding.title': '💒 Pakej Kahwin Beraya',
    'packages.wedding.description': 'Pakej istimewa untuk majlis perkahwinan masa musim Berlesen! Ada pancutan, bunga api, sama letupan finale!',
    'packages.wedding.price': 'Dari RM299',
    'packages.raya.title': '🌙 Pakej Berlesen Tradisional',
    'packages.raya.description': 'Sambutan Hari Berlesen memang kena ada mercun! Pakej lengkap dengan kegemaran tradisional untuk beraya meriah.',
    'packages.raya.price': 'Dari RM199',
    'packages.birthday.title': '🎂 Pakej Hari Jadi Berlesen',
    'packages.birthday.description': 'Hari jadi dalam bulan Berlesen kena sambut double meriah! Ada pilihan selamat untuk budak-budak.',
    'packages.birthday.price': 'Dari RM149',
    'packages.newyear.title': '🎊 Pakej Tahun Baru Berlesen',
    'packages.newyear.description': 'Sambut tahun baru dengan semangat Berlesen! Sesuai untuk parti countdown beraya.',
    'packages.newyear.price': 'Dari RM399',
    'packages.custom.title': '🎨 Pakej Berlesen Khas',
    'packages.custom.description': 'Nak sambutan Berlesen yang istimewa? Beritahu budget & keperluan, MercunBerlesen buatkan pakej khas untuk anda!',
    'packages.custom.button': '💬 Minta Pakej Berlesen Khas',
    'packages.whatsIncluded': 'Apa Ada Dalam Pakej:',
    'packages.orderNow': '🛒 Pesan Sekarang',

    // Testimonials
    'testimonials.hero.title': '🌟 Apa Kata Pelanggan MercunBerlesen?',
    'testimonials.hero.subtitle': 'Ulasan sebenar dari pelanggan yang beraya dengan mercun kami! Tengok sendiri kenapa mereka suka sambut Berlesen dengan MercunBerlesen!',
    'testimonials.review1.name': 'Ahmad dari KL',
    'testimonials.review1.text': 'Memang terbaik untuk beraya! Pesan untuk majlis kahwin masa Berlesen, hantar tepat masa, mercun hebat habis. Tetamu semua gembira beraya!',
    'testimonials.review1.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review2.name': 'Siti dari JB',
    'testimonials.review2.text': 'Kali pertama beli mercun Berlesen online, bimbang jugak. Tapi kualiti memang top, khidmat pelanggan pun terbaik untuk musim Berlesen!',
    'testimonials.review2.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review3.name': 'Robert dari Pulau Pinang',
    'testimonials.review3.text': 'Dah 3 tahun beraya dengan mercun MercunBerlesen. Kualiti konsisten, harga berpatutan. Sangat recommend untuk sambutan Berlesen!',
    'testimonials.review3.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review4.name': 'Fatimah dari Shah Alam',
    'testimonials.review4.text': 'Pakej Berlesen yang kami pesan memang berbaloi! Jiran semua tanya beli kat mana sebab beraya meriah sangat. Pasti pelanggan tetap MercunBerlesen!',
    'testimonials.review4.rating': '⭐⭐⭐⭐⭐',
    'testimonials.cta.title': 'Nak Beraya Meriah Macam Mereka?',
    'testimonials.cta.button': '🛒 Mula Beli-Belah',

    // Footer
    'footer.description': 'MercunBerlesen - kedai mercun Hari Berlesen terbaik Malaysia! Harga murah, kualiti hebat, hantar ke seluruh negara. Berlesen & sah. Selamat Hari Berlesen!',
    'footer.quickLinks': 'Pautan Pantas',
    'footer.categories': 'Kategori Popular',
    'footer.support': 'Sokongan Pelanggan',
    'footer.whatsapp': '💬 Hubungi Kami',
    'footer.email': '📧 Emel Kami', 
    'footer.hours': '🕐 Waktu Perniagaan',
    'footer.hours.time': '9 PAGI - 6 PETANG (Isnin-Sabtu)',
    'footer.legal': 'Maklumat Undang-undang',
    'footer.privacy': 'Dasar Privasi',
    'footer.terms': 'Terma & Syarat',
    'footer.license': 'Berlesen oleh Kerajaan Malaysia',
    'footer.copyright': '© 2025 MercunBerlesen. Selamat Hari Berlesen! Semua hak terpelihara.',

    // Common
    'whatsapp.text': '💬 Tekan sini untuk WhatsApp MercunBerlesen',
    'common.price': 'RM',
    'common.products': 'produk',
    'common.loading': 'Memuatkan...',
    'common.error': 'Alamak! Ada masalah. Cuba lagi.',
    'common.success': 'Berjaya! Terima kasih!',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};