import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ms';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.fireworks': 'Fireworks & Sparklers',
    'nav.packages': 'Event Packages',
    'nav.permitGuide': 'Permit Guide',
    'nav.safetyGuide': 'Safety Tips',
    'nav.testimonials': 'Reviews',
    'nav.contact': 'Contact Us',
    
    // Homepage
    'home.hero.title': 'BMFireworks — Malaysia’s Licensed Fireworks Partner',
    'home.hero.subtitle': '100% Legal • Premium Quality • Event-Ready Support',
    'home.hero.description': 'Bearboom × BMFireworks delivers licensed fireworks with complete documentation, permit guidance, and on-ground coordination for weddings, festive celebrations, and corporate activations.',
    'home.hero.viewFireworks': 'View Full Catalogue',
    'home.section.title': 'What Experience Are You Planning?',
    'home.section.description': 'From Raya open houses to countdown finales, our team recommends the right effects, permit steps, and safety preparations.',
    'home.card.fireworks.title': 'Curated Fireworks Library',
    'home.card.fireworks.description': 'Browse 100+ licensed items — handheld sparklers, aerial cakes, rockets, and professional finale shells.',
    'home.card.packages.title': 'Ready-to-Run Packages',
    'home.card.packages.description': 'Save time with themed combinations for weddings, community events, and brand launches. Permit templates included.',
    'home.card.permit.title': 'Permit Advisory',
    'home.card.permit.description': 'We supply checklists, templates, and coaching so your PDRM application is submitted right the first time.',
    'home.why.title': 'Why partners choose Bearboom × BMFireworks',
    'home.why.licensed': '✅ Licensed & Compliant',
    'home.why.licensed.desc': 'Registered supplier with audited storage and government-approved inventory.',
    'home.why.products': '🎆 Extensive Inventory',
    'home.why.products.desc': 'Eight product categories covering family-friendly sparklers up to stadium-size finale cakes.',
    'home.why.permit': '📝 Permit Guidance',
    'home.why.permit.desc': 'Step-by-step advisory for PDRM submissions, local council notifications, and event timings.',
    'home.why.support': '💬 Responsive Support',
    'home.why.support.desc': 'Dedicated WhatsApp line, reference videos, and optional on-site coordination.',

    // Price download
    'price.section.title': 'Need the latest price list?',
    'price.section.description': 'Fill out this quick form and receive the current catalogue instantly. The PDF download starts right after submission.',
    'price.section.button': 'Fill form & download price list',
    'price.form.title': 'Contact details',
    'price.form.nameLabel': 'Full name',
    'price.form.namePlaceholder': 'e.g. Ahmad Firdaus',
    'price.form.phoneLabel': 'Phone number',
    'price.form.phonePlaceholder': 'e.g. 012 345 6789',
    'price.form.stateLabel': 'State (Peninsular Malaysia)',
    'price.form.statePlaceholder': 'Select state',
    'price.form.submit': 'Submit & download PDF',
    'price.form.processing': 'Processing…',
    'price.form.note': 'We only follow up to confirm stock availability and wholesale packages. Zero spam.',
    'price.form.error.name': 'Please enter your full name.',
    'price.form.error.phone': 'Please provide a valid phone number.',
    'price.form.error.state': 'Please choose your state.',
    'price.form.error.technical': 'Download is ready, but your details could not be saved. We will reconcile manually.',
    'price.downloadFilename': 'bmfireworks-price-list.pdf',

    // Factory section
    'factory.section.badge': 'Licensed factory network',
    'factory.section.title': 'Four Bearboom × BMFireworks factories on standby',
    'factory.section.description': 'Every facility is operated with government-approved SOPs to ensure compliant inventory and reliable bulk deliveries.',
    'factory.section.cta': 'Schedule site visit & bulk stock pickup',
    'factory.section.note': 'Visits are by appointment only for serious resellers, event planners, and wholesale buyers.',
    'factory.cards.seelong.location': 'Seelong, Johor',
    'factory.cards.seelong.role': 'HQ & Primary Production',
    'factory.cards.seelong.description': 'Largest production capacity with premium fireworks stocked year-round.',
    'factory.cards.seelong.strength': 'Quality control hub and private-label packaging for partners.',
    'factory.cards.muar.location': 'Muar, Johor',
    'factory.cards.muar.role': 'Southern Wholesale & Event Hub',
    'factory.cards.muar.description': 'Specialised in bundling event kits and fulfilling wholesale orders across the South.',
    'factory.cards.muar.strength': 'Rapid truck loading bays for daily dispatch.',
    'factory.cards.simpangRenggam.location': 'Simpang Renggam, Johor',
    'factory.cards.simpangRenggam.role': 'Fulfilment & Repack Facility',
    'factory.cards.simpangRenggam.description': 'Dedicated crew for reseller repacks and custom customer branding.',
    'factory.cards.simpangRenggam.strength': 'Custom packages for wedding planners, event organisers, and bazaar sellers.',
    'factory.cards.ipoh.location': 'Ipoh, Perak',
    'factory.cards.ipoh.role': 'Central & Northern Distribution',
    'factory.cards.ipoh.description': 'Maintains buffer stock for West Coast and northern state deliveries.',
    'factory.cards.ipoh.strength': 'Fast turnaround to Perak, Penang, and Greater Klang Valley.',

    // Peak season section
    'peak.section.badge': 'Annual sales surges',
    'peak.section.title': 'Major festivals drive massive sales',
    'peak.section.description': 'Bearboom × BMFireworks products fly off the shelves during these peak celebrations. Secure inventory early to multiply your revenue.',
    'peak.section.note': 'We help you lock supply and plan marketing so you never run out during the busiest festive weeks.',
    'peak.cards.deepavali.festival': 'Deepavali',
    'peak.cards.deepavali.period': 'Sep – Nov',
    'peak.cards.deepavali.description': 'Colourful aerials and community event packages in constant demand.',
    'peak.cards.deepavali.opportunity': 'Retail sales spike 2–3×; temple and family bundles move fastest.',
    'peak.cards.aidilfitri.festival': 'Hari Raya Aidilfitri',
    'peak.cards.aidilfitri.period': 'Mar – Apr',
    'peak.cards.aidilfitri.description': 'Village celebrations and buka puasa gatherings need family-friendly effects.',
    'peak.cards.aidilfitri.opportunity': 'Secure stock early—family and kids bundles sell out quickly.',
    'peak.cards.cny.festival': 'Chinese New Year',
    'peak.cards.cny.period': 'Dec – Feb',
    'peak.cards.cny.description': 'Restaurants and family reunions require multi-shot cakes, rockets, and finales.',
    'peak.cards.cny.opportunity': 'Highest wholesale volume of the year—perfect for premium combos.',
    'peak.cards.christmas.festival': 'Christmas & New Year Countdown',
    'peak.cards.christmas.period': 'Nov – Jan',
    'peak.cards.christmas.description': 'Hotels, event planners, and city squares commission professional displays.',
    'peak.cards.christmas.opportunity': 'High-margin showcase packages with optional installation services.',

    // States (Peninsular Malaysia)
    'states.johor': 'Johor',
    'states.kedah': 'Kedah',
    'states.kelantan': 'Kelantan',
    'states.melaka': 'Melaka',
    'states.negeriSembilan': 'Negeri Sembilan',
    'states.pahang': 'Pahang',
    'states.perak': 'Perak',
    'states.perlis': 'Perlis',
    'states.pulauPinang': 'Penang',
    'states.selangor': 'Selangor',
    'states.terengganu': 'Terengganu',
    'states.wilayahPersekutuanKualaLumpur': 'Kuala Lumpur (Federal Territory)',
    'states.wilayahPersekutuanPutrajaya': 'Putrajaya (Federal Territory)',
    
    // Products
    'products.title': 'Fireworks Catalogue',
    'products.description': 'Filter by category, view demo videos, and add licensed products to your order. Delivery available across Malaysia.',
    'products.search.placeholder': 'Search by product name or keyword…',
    'products.category.all': 'All Products',
    'products.category.premium': 'Specialty Cakes & Finales',
    'products.category.sparkle': 'Sparkles & Handhelds',
    'products.category.kidsFirecrackers': 'Kid-Friendly Picks',
    'products.category.poppop': 'Pop-Pop & Novelty',
    'products.category.fountainBlast': 'Fountains & Ground FX',
    'products.category.oneshot': 'Single Shot / Thunder',
    'products.category.rocket': 'Rockets & Flyers',
    'products.category.reddragon': 'Red Dragon Classics',
    'products.noResults': 'No products matched your search. Try another keyword or category.',
    'products.addToCart': 'Add to cart',
    'products.watchVideo': 'Watch demo',
    
    // Safety Guide
    'safety.hero.title': 'Safety First',
    'safety.hero.subtitle': 'Use licensed fireworks responsibly so every celebration stays memorable and compliant.',
    'safety.warning.title': '⚠️ Important reminder',
    'safety.warning.description': 'Only trained adults should handle ignition. Always follow the permit timing and location requirements.',
    'safety.tips.title': 'Quick safety tips',
    'safety.tip1.title': '👨‍👩‍👧‍👦 Adult supervision only',
    'safety.tip1.desc': 'Assign a responsible adult to manage lighting and crowd distance at all times.',
    'safety.tip2.title': '👓 Protective gear',
    'safety.tip2.desc': 'Keep faces away from ignition points and provide eye protection for crew members.',
    'safety.tip3.title': '🏃‍♂️ Safe perimeter',
    'safety.tip3.desc': 'Mark a minimum 8–10 metre exclusion zone around the launch area.',
    'safety.tip4.title': '🚿 Water on standby',
    'safety.tip4.desc': 'Prepare buckets of water or an extinguisher before lighting any effect.',
    'safety.steps.title': 'Step-by-step checklist',
    'safety.before.title': '📋 Before lighting',
    'safety.before.step1': 'Read the instructions for every item in the show sequence.',
    'safety.before.step2': 'Clear the launch zone of debris and flammable materials.',
    'safety.before.step3': 'Set up safety gear, barricades, and emergency water.',
    'safety.before.step4': 'Brief the team on the firing order and emergency plan.',
    'safety.before.step5': 'Verify permit timings and inform neighbours when necessary.',
    'safety.during.title': '🔥 During the show',
    'safety.during.step1': 'Ignite one item at a time using a long lighter or punk stick.',
    'safety.during.step2': 'Move to a safe distance immediately after lighting.',
    'safety.during.step3': 'Do not lean over effects once the fuse is lit.',
    'safety.during.step4': 'If an item misfires, wait 20 minutes and soak it before disposal.',
    'safety.during.step5': 'Keep pets and children indoors throughout the display.',
    'safety.after.title': '🧹 After the display',
    'safety.after.step1': 'Allow debris to cool before handling.',
    'safety.after.step2': 'Soak spent shells and misfires in water before disposal.',
    'safety.after.step3': 'Dispose of all remnants in sealed rubbish bags.',
    'safety.emergency.title': '🚨 Emergency contacts',
    'safety.emergency.description': 'Contact the authorities immediately if unexpected incidents occur.',
    'safety.emergency.numbers': 'Emergency Numbers',
    'safety.emergency.fire': '🚒 Fire Department: 994',
    'safety.emergency.police': '👮‍♂️ Police: 999',
    'safety.emergency.ambulance': '🚑 Ambulance: 999',

    // Permit Guide
    'permit.hero.title': 'Permit paperwork made simple',
    'permit.hero.subtitle': 'We prepare document checklists, templates, and submission timelines for PDRM and local councils.',
    'permit.requirements.title': 'Documents you will need',
    'permit.requirements.step1': 'Company or organiser identification (IC/ROC).',
    'permit.requirements.step2': 'Venue approval letter from the relevant municipal council.',
    'permit.requirements.step3': 'Site plan with launch and safety zones marked clearly.',
    'permit.requirements.step4': 'Insurance coverage or indemnity letter for public events.',
    'permit.process.title': 'Permit submission flow',
    'permit.process.step1': 'Collect supporting letters and risk assessments.',
    'permit.process.step2': 'Submit the application at the nearest district police station.',
    'permit.process.step3': 'Provide fire department notification when required.',
    'permit.process.step4': 'Settle processing fees and keep receipts for inspection.',
    'permit.process.step5': 'Await written approval before scheduling rehearsals.',
    'permit.tips.title': 'Helpful tips',
    'permit.tips.tip1': 'Apply at least 14 working days before the event.',
    'permit.tips.tip2': 'Attach photos or videos of previous shows to build confidence.',
    'permit.tips.tip3': 'Maintain a spreadsheet of who signs each form and when.',
    'permit.tips.tip4': 'Review safety briefing notes with the local police liaison.',
    'permit.help.title': 'Need an experienced coordinator?',
    'permit.help.description': 'Contact our team and we will walk you through each requirement, including on-site standby options.',

    // Contact
    'contact.hero.title': 'Talk to our fireworks specialists',
    'contact.hero.subtitle': 'Share your event concept, budget, and permit timeline — we will propose a compliant solution within 24 hours.',
    'contact.whatsapp.title': 'WhatsApp consultation',
    'contact.whatsapp.description': 'Fastest response. Our team replies within business hours with suggestions and availability.',
    'contact.whatsapp.number': '+60 13-734 0415',
    'contact.whatsapp.button': 'Start WhatsApp chat',
    'contact.email.title': 'Email enquiries',
    'contact.email.description': 'Send detailed briefs, technical riders, or procurement documents to our inbox.',
    'contact.email.address': 'hello@bmfirework.com',
    'contact.hours.title': 'Office hours',
    'contact.hours.weekdays': 'Monday – Friday: 9.00am – 6.00pm',
    'contact.hours.saturday': 'Saturday: 9.00am – 2.00pm',
    'contact.hours.sunday': 'Sunday & public holidays: On-call only',
    'contact.location.title': 'Showroom & logistics hub',
    'contact.location.address': 'Klang Valley operations centre (exact location shared after permit confirmation).',

    // Cart
    'cart.title': 'Your Quote Summary',
    'cart.empty': 'No products selected yet. Browse the catalogue to build your order.',
    'cart.empty.button': 'Browse fireworks',
    'cart.item.remove': 'Remove',
    'cart.item.quantity': 'Quantity',
    'cart.subtotal': 'Subtotal',
    'cart.delivery': 'Logistics estimate',
    'cart.total': 'Projected total',
    'cart.checkout': 'Request quotation',
    'cart.continue': 'Continue browsing',
    'cart.delivery.note': 'Delivery fees vary by volume and destination. Our team will confirm in the official quotation.',
    'cart.update': 'Update',
    'cart.clear': 'Clear selection',

    // Packages
    'packages.hero.title': 'Curated fireworks programmes',
    'packages.hero.subtitle': 'Choose a pre-built package or request a custom show engineered around your venue and budget.',
    'packages.wedding.title': 'Wedding highlight packages',
    'packages.wedding.description': 'Romantic sparkler entrances, cake fountains, and choreographed finales for ballroom or outdoor receptions.',
    'packages.wedding.price': 'From RM299',
    'packages.raya.title': 'Festive open house bundles',
    'packages.raya.description': 'Family-friendly mixes with managed sound levels and safety signage for residential celebrations.',
    'packages.raya.price': 'From RM199',
    'packages.birthday.title': 'Birthday & private party sets',
    'packages.birthday.description': 'Handheld sparklers, low-level fountains, and surprise bursts tailored to home compounds or boutique venues.',
    'packages.birthday.price': 'From RM149',
    'packages.newyear.title': 'Countdown spectacles',
    'packages.newyear.description': 'High-impact aerial cakes, timed finales, and music-sync options for corporate or public countdowns.',
    'packages.newyear.price': 'From RM399',
    'packages.custom.title': 'Design a custom display',
    'packages.custom.description': 'Share your concept and we will assemble a licensed show sequence, crew, and permit documentation.',
    'packages.custom.button': 'Request custom plan',
    'packages.whatsIncluded': 'Package includes',
    'packages.orderNow': 'Request quotation',

    // Testimonials
    'testimonials.hero.title': 'Partners who trust BMFireworks',
    'testimonials.hero.subtitle': 'Event planners, resorts, and corporate teams share how our crew supported their celebrations.',
    'testimonials.review1.name': 'Azlan • Event Planner (KL)',
    'testimonials.review1.text': '“Bearboom × BMFireworks handled permit submission, rehearsal, and finale cueing flawlessly. Client was impressed with the professionalism.”',
    'testimonials.review1.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review2.name': 'Melissa • Resort Manager (Langkawi)',
    'testimonials.review2.text': '“They supplied a customised beachfront show with clear safety briefings and on-site standby. Zero incidents, maximum wow factor.”',
    'testimonials.review2.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review3.name': 'Iqbal • Wedding Planner (Penang)',
    'testimonials.review3.text': '“From handheld sparklers to a surprise aerial finale, everything was delivered on time with proper licensing. Highly recommended.”',
    'testimonials.review3.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review4.name': 'Samantha • Brand Activation Lead',
    'testimonials.review4.text': '“Great communication, detailed risk assessments, and edit-friendly show files for our approval process. Will book again next quarter.”',
    'testimonials.review4.rating': '⭐⭐⭐⭐⭐',
    'testimonials.cta.title': 'Plan your next celebration with us',
    'testimonials.cta.button': 'Schedule a consultation',

    // Footer
    'footer.description': 'Bearboom × BMFireworks is Malaysia’s trusted partner for licensed fireworks, permit advisory, and event support.',
    'footer.quickLinks': 'Quick links',
    'footer.links.catalogue': 'Product catalogue',
    'footer.links.packages': 'Event packages',
    'footer.links.permit': 'Permit guide',
    'footer.links.safety': 'Safety guide',
    'footer.links.testimonials': 'Testimonials',
    'footer.links.contact': 'Contact us',
    'footer.categories': 'Popular categories',
    'footer.support': 'Customer support',
    'footer.whatsapp': 'WhatsApp',
    'footer.email': 'Email', 
    'footer.contact.title': 'Contact',
    'footer.contact.phone': '📱 WhatsApp: +60 13-734 0415',
    'footer.contact.email': '📧 Email: hello@bmfirework.com',
    'footer.contact.hours': '🕒 Mon–Sat: 9AM–6PM',
    'footer.contact.location': '📍 Kuala Lumpur, Malaysia',
    'footer.hours': 'Operating hours',
    'footer.hours.time': 'Mon–Fri 9am–6pm • Sat 9am–2pm',
    'footer.partnership': 'Bearboom × BMFireworks Partnership 🎆',
    'footer.legalNote': 'Operations comply with Malaysian fireworks licensing guidelines.',
    'footer.legal': 'Legal info',
    'footer.privacy': 'Privacy policy',
    'footer.terms': 'Terms & conditions',
    'footer.license': 'Licensed supplier • SSM & PDRM-compliant',
    'footer.copyright': '© 2025 BMFireworks. All rights reserved.',

    // Common
    'whatsapp.text': '💬 Tekan sini untuk WhatsApp BMFireworks',
    'common.price': 'RM',
    'common.products': 'products',
    'common.loading': 'Loading...',
    'common.error': 'Oops! There\'s an error. Try again.',
    'common.success': 'Success! Thank you!',
  },
  
  ms: {
    // Navigation
    'nav.home': 'Utama',
    'nav.fireworks': 'Mercun & Bunga Api',
    'nav.packages': 'Pakej raya',
    'nav.permitGuide': 'Panduan Permit',
    'nav.safetyGuide': 'Tips Keselamatan',
    'nav.testimonials': 'Ulasan',
    'nav.contact': 'Hubungi Kami',
    
    // Homepage
    'home.hero.title': 'BMFireworks — Rakan Mercun Berlesen Malaysia',
    'home.hero.subtitle': '100% Sah • Stok Premium • Support Acara',
    'home.hero.description': 'Bearboom × BMFireworks sediakan mercun berlesen lengkap dengan dokumen, nasihat permit dan crew acara untuk perkahwinan, korporat serta perayaan.',
    'home.hero.viewFireworks': 'Lihat Semua Produk',
    'home.section.title': 'Acara apa yang anda rancang?',
    'home.section.description': 'Daripada open house raya hingga countdown tahun baru, kami cadangkan kombinasi efek, panduan permit dan langkah keselamatan.',
    'home.card.fireworks.title': 'Perpustakaan Mercun Lengkap',
    'home.card.fireworks.description': 'Pilih lebih 100 item berlesen — sparklers, aerial cake, roket dan finale profesional.',
    'home.card.packages.title': 'Pakej Siap Guna',
    'home.card.packages.description': 'Jimatan masa dengan pakej bertema untuk kahwin, komuniti dan aktivasi jenama. Template permit turut disertakan.',
    'home.card.permit.title': 'Bantuan Permit',
    'home.card.permit.description': 'Kami sediakan senarai semak, contoh surat dan coaching supaya permohonan PDRM diluluskan tanpa drama.',
    'home.why.title': 'Kenapa pilih Bearboom × BMFireworks',
    'home.why.licensed': '✅ Berlesen & Pematuhan',
    'home.why.licensed.desc': 'Pembekal berdaftar dengan stor beraudit serta stok diluluskan agensi kerajaan.', 
    'home.why.products': '🎆 Inventori Menyeluruh',
    'home.why.products.desc': 'Lapan kategori produk merangkumi sparklers keluarga hingga cake finale skala stadium.',
    'home.why.permit': '📝 Panduan Permit',
    'home.why.permit.desc': 'Langkah demi langkah untuk permohonan PDRM, notis PBT dan jadual acara.',
    'home.why.support': '💬 Sokongan Pantas',
    'home.why.support.desc': 'WhatsApp khusus, rujukan video dan pilihan crew standby di lokasi.',

    // Price download
    'price.section.title': 'Nak harga terkini?',
    'price.section.description': 'Isi borang ringkas ini untuk dapatkan katalog semasa. Muat turun PDF bermula sebaik borang dihantar.',
    'price.section.button': 'Isi borang & muat turun harga',
    'price.form.title': 'Maklumat hubungan',
    'price.form.nameLabel': 'Nama penuh',
    'price.form.namePlaceholder': 'Contoh: Ahmad Firdaus',
    'price.form.phoneLabel': 'Nombor telefon',
    'price.form.phonePlaceholder': 'Contoh: 012 345 6789',
    'price.form.stateLabel': 'Negeri (Semenanjung Malaysia)',
    'price.form.statePlaceholder': 'Pilih negeri',
    'price.form.submit': 'Hantar & muat turun PDF',
    'price.form.processing': 'Sedang diproses…',
    'price.form.note': 'Kami hanya hubungi semula untuk sahkan stok dan pakej borong. Tiada spam.',
    'price.form.error.name': 'Sila masukkan nama penuh anda.',
    'price.form.error.phone': 'Sila masukkan nombor telefon yang sah.',
    'price.form.error.state': 'Sila pilih negeri anda.',
    'price.form.error.technical': 'Muat turun tersedia, tetapi maklumat anda gagal disimpan. Kami akan rekod secara manual.',
    'price.downloadFilename': 'bmfireworks-senarai-harga.pdf',

    // Factory section
    'factory.section.badge': 'Rangkaian kilang berlesen',
    'factory.section.title': '4 kilang Bearboom × BMFireworks sedia stok',
    'factory.section.description': 'Setiap fasiliti beroperasi dengan SOP diluluskan kerajaan untuk menjamin stok patuh dan penghantaran pukal yang lancar.',
    'factory.section.cta': 'Tempah lawatan gudang & pengambilan stok borong',
    'factory.section.note': 'Lawatan hanya melalui temujanji untuk reseller serius, event planner dan pembeli borong.',
    'factory.cards.seelong.location': 'Seelong, Johor',
    'factory.cards.seelong.role': 'HQ & Pengeluaran Utama',
    'factory.cards.seelong.description': 'Kapasiti pengeluaran terbesar dengan stok premium sepanjang tahun.',
    'factory.cards.seelong.strength': 'Hab kawalan kualiti serta pembungkusan label pelanggan.',
    'factory.cards.muar.location': 'Muar, Johor',
    'factory.cards.muar.role': 'Hab Borong & Acara Selatan',
    'factory.cards.muar.description': 'Pakar dalam set acara dan permintaan borong seluruh Zon Selatan.',
    'factory.cards.muar.strength': 'Lorong loading pantas untuk penghantaran setiap hari.',
    'factory.cards.simpangRenggam.location': 'Simpang Renggam, Johor',
    'factory.cards.simpangRenggam.role': 'Pusat Fulfillment & Repack',
    'factory.cards.simpangRenggam.description': 'Krew khas untuk repack reseller dan label khas pelanggan.',
    'factory.cards.simpangRenggam.strength': 'Pakej custom untuk wedding planner, penganjur acara dan peniaga bazar.',
    'factory.cards.ipoh.location': 'Ipoh, Perak',
    'factory.cards.ipoh.role': 'Distribusi Tengah & Utara',
    'factory.cards.ipoh.description': 'Menyimpan stok buffer untuk penghantaran pantai barat hingga negeri utara.',
    'factory.cards.ipoh.strength': 'Penghantaran pantas ke Perak, Pulau Pinang dan Lembah Klang.',

    // Peak season section
    'peak.section.badge': 'Lonjakan jualan tahunan',
    'peak.section.title': 'Perayaan besar = jualan meletup',
    'peak.section.description': 'Produk Bearboom × BMFireworks sentiasa habis ketika musim puncak ini. Kunci stok awal untuk gandakan jualan anda.',
    'peak.section.note': 'Kami bantu anda kunci bekalan dan kempen supaya jualan tak putus sepanjang musim perayaan.',
    'peak.cards.deepavali.festival': 'Deepavali',
    'peak.cards.deepavali.period': 'Sep – Nov',
    'peak.cards.deepavali.description': 'Permintaan tinggi untuk bancuhan warna-warni dan pakej komuniti.',
    'peak.cards.deepavali.opportunity': 'Jualan runcit naik 2–3×; bundle kuil dan keluarga paling laris.',
    'peak.cards.aidilfitri.festival': 'Hari Raya Aidilfitri',
    'peak.cards.aidilfitri.period': 'Mac – Apr',
    'peak.cards.aidilfitri.description': 'Kampung dan majlis berbuka perlukan set mesra keluarga.',
    'peak.cards.aidilfitri.opportunity': 'Kunci stok lebih awal kerana pakej keluarga dan kanak-kanak cepat habis.',
    'peak.cards.cny.festival': 'Tahun Baru Cina',
    'peak.cards.cny.period': 'Dis – Feb',
    'peak.cards.cny.description': 'Keluarga dan restoran perlukan cake berbilang tembakan, roket dan finale.',
    'peak.cards.cny.opportunity': 'Volume borong tertinggi setahun—sesuai untuk combo premium.',
    'peak.cards.christmas.festival': 'Krismas & Countdown Tahun Baru',
    'peak.cards.christmas.period': 'Nov – Jan',
    'peak.cards.christmas.description': 'Hotel, event planner dan bandar perlukan show profesional.',
    'peak.cards.christmas.opportunity': 'Margin tinggi untuk pakej showcase beserta pemasangan tapak.',

    // States (Semenanjung Malaysia)
    'states.johor': 'Johor',
    'states.kedah': 'Kedah',
    'states.kelantan': 'Kelantan',
    'states.melaka': 'Melaka',
    'states.negeriSembilan': 'Negeri Sembilan',
    'states.pahang': 'Pahang',
    'states.perak': 'Perak',
    'states.perlis': 'Perlis',
    'states.pulauPinang': 'Pulau Pinang',
    'states.selangor': 'Selangor',
    'states.terengganu': 'Terengganu',
    'states.wilayahPersekutuanKualaLumpur': 'Wilayah Persekutuan Kuala Lumpur',
    'states.wilayahPersekutuanPutrajaya': 'Wilayah Persekutuan Putrajaya',
    
    // Products
    'products.title': 'Senarai Mercun',
    'products.description': 'Tapis ikut kategori, tonton video demo dan tambah barangan berlesen ke senarai pesanan anda. Penghantaran tersedia di seluruh Malaysia.',
    'products.search.placeholder': 'Cari nama produk atau kata kunci…',
    'products.category.all': 'Semua Produk',
    'products.category.premium': 'Cake & Finale Istimewa',
    'products.category.sparkle': 'Sparkler & Handheld',
    'products.category.kidsFirecrackers': 'Pilihan Mesra Kanak-kanak',
    'products.category.poppop': 'Pop-Pop & Novelti',
    'products.category.fountainBlast': 'Fountain & Ground FX',
    'products.category.oneshot': 'Single Shot / Thunder',
    'products.category.rocket': 'Roket & Penerbangan',
    'products.category.reddragon': 'Red Dragon Classics',
    'products.noResults': 'Maaf, tiada produk sepadan. Cuba kata kunci atau kategori lain.',
    'products.addToCart': 'Tambah ke senarai',
    'products.watchVideo': 'Tonton demo',
    
    // Safety Guide
    'safety.hero.title': 'Utamakan keselamatan',
    'safety.hero.subtitle': 'Gunakan mercun berlesen secara terancang supaya setiap acara kekal meriah dan sah.',
    'safety.warning.title': '⚠️ Peringatan penting',
    'safety.warning.description': 'Hanya kru dewasa terlatih dibenarkan mengendalikan percikan. Ikut masa dan lokasi yang diluluskan dalam permit.',
    'safety.tips.title': 'Tip pantas keselamatan',
    'safety.tip1.title': '👨‍👩‍👧‍👦 Awasan dewasa',
    'safety.tip1.desc': 'Lantik penyelia bertanggungjawab untuk kawal jarak orang ramai sepanjang pertunjukan.',
    'safety.tip2.title': '👓 Peralatan perlindungan',
    'safety.tip2.desc': 'Elak muka daripada kawasan sumbu dan sediakan pelindung mata untuk kru.',
    'safety.tip3.title': '🏃‍♂️ Zon selamat',
    'safety.tip3.desc': 'Tandakan zon larangan sekurang-kurangnya 8–10 meter dari kawasan pelancaran.',
    'safety.tip4.title': '🚿 Air standby',
    'safety.tip4.desc': 'Sediakan baldi air atau alat pemadam sebelum menyalakan sebarang efek.',
    'safety.steps.title': 'Langkah demi langkah',
    'safety.before.title': '📋 Sebelum nyala',
    'safety.before.step1': 'Baca arahan setiap item mengikut turutan pertunjukan.',
    'safety.before.step2': 'Kosongkan kawasan pelancaran daripada objek dan bahan mudah terbakar.',
    'safety.before.step3': 'Letak peralatan keselamatan, penghadang dan sumber air kecemasan.',
    'safety.before.step4': 'Brief kru tentang urutan tembakan serta pelan kecemasan.',
    'safety.before.step5': 'Sahkan masa permit dan maklumkan jiran jika perlu.',
    'safety.during.title': '🔥 Semasa pertunjukan',
    'safety.during.step1': 'Nyalakan satu item pada satu masa guna pemetik panjang.',
    'safety.during.step2': 'Berundur segera ke zon selamat selepas menyalakan.',
    'safety.during.step3': 'Jangan bongkok ke arah efek selepas sumbu dinyalakan.',
    'safety.during.step4': 'Jika misfire, tunggu 20 minit sebelum rendam dan lupuskan.',
    'safety.during.step5': 'Pastikan haiwan peliharaan dan kanak-kanak berada di dalam rumah.',
    'safety.after.title': '🧹 Selepas pertunjukan',
    'safety.after.step1': 'Biarkan sisa sejuk sebelum menyentuhnya.',
    'safety.after.step2': 'Rendam casing dan item misfire sebelum dibuang.',
    'safety.after.step3': 'Buang semua sisa dalam beg sampah tertutup.',
    'safety.emergency.title': '🚨 Nombor kecemasan',
    'safety.emergency.description': 'Hubungi pihak berkuasa segera jika berlaku insiden di luar jangka.',
    'safety.emergency.numbers': 'Nombor Kecemasan',
    'safety.emergency.fire': '🚒 Bomba: 994',
    'safety.emergency.police': '👮‍♂️ Polis: 999',
    'safety.emergency.ambulance': '🚑 Ambulans: 999',

    // Permit Guide
    'permit.hero.title': 'Proses permit jadi mudah',
    'permit.hero.subtitle': 'Kami siap dengan senarai dokumen, contoh surat dan jadual serahan untuk PDRM serta PBT.',
    'permit.requirements.title': 'Dokumen diperlukan',
    'permit.requirements.step1': 'Salinan IC/SSM penganjur atau syarikat.',
    'permit.requirements.step2': 'Surat sokongan lokasi daripada majlis perbandaran berkaitan.',
    'permit.requirements.step3': 'Pelan tapak lengkap dengan zon pelancaran dan garis keselamatan.',
    'permit.requirements.step4': 'Polisi insurans atau surat tanggungan untuk acara awam.',
    'permit.process.title': 'Aliran serahan permit',
    'permit.process.step1': 'Kumpul semua dokumen sokongan dan penilaian risiko.',
    'permit.process.step2': 'Serah borang di balai polis daerah terdekat.',
    'permit.process.step3': 'Maklumkan bomba jika perlu untuk pemeriksaan lokasi.',
    'permit.process.step4': 'Selesaikan bayaran pemprosesan dan simpan resit.',
    'permit.process.step5': 'Tunggu kelulusan bertulis sebelum jadualkan latihan.',
    'permit.tips.title': 'Tip berguna',
    'permit.tips.tip1': 'Mohon sekurang-kurangnya 14 hari bekerja sebelum acara.',
    'permit.tips.tip2': 'Lampirkan foto atau video show terdahulu sebagai rujukan.',
    'permit.tips.tip3': 'Catat siapa tanda tangan setiap dokumen dan tarikh serahan.',
    'permit.tips.tip4': 'Semak nota taklimat keselamatan bersama pegawai liaison polis.',
    'permit.help.title': 'Perlu bantuan penuh?',
    'permit.help.description': 'Hubungi kami dan kami akan bimbing setiap langkah hingga permit lulus, termasuk opsyen crew standby.',

    // Contact
    'contact.hero.title': 'Berbincang dengan pasukan mercun kami',
    'contact.hero.subtitle': 'Kongsi idea acara, bajet dan tarikh permit — kami cadangkan solusi patuh peraturan dalam 24 jam.',
    'contact.whatsapp.title': 'Sesi WhatsApp',
    'contact.whatsapp.description': 'Respons terpantas. Team kami balas pada waktu pejabat dengan cadangan dan slot tersedia.',
    'contact.whatsapp.number': '+60 13-734 0415',
    'contact.whatsapp.button': 'Mula chat WhatsApp',
    'contact.email.title': 'Emel pertanyaan',
    'contact.email.description': 'Hantar brief lengkap, rider teknikal atau dokumen perolehan ke peti mel kami.',
    'contact.email.address': 'hello@bmfirework.com',
    'contact.hours.title': 'Waktu operasi',
    'contact.hours.weekdays': 'Isnin – Jumaat: 9.00 pagi – 6.00 petang',
    'contact.hours.saturday': 'Sabtu: 9.00 pagi – 2.00 petang',
    'contact.hours.sunday': 'Ahad & cuti umum: On-call sahaja',
    'contact.location.title': 'Showroom & hub logistik',
    'contact.location.address': 'Klang Valley (lokasi tepat dikongsi selepas pengesahan permit).',

    // Cart
    'cart.title': 'Ringkasan sebut harga',
    'cart.empty': 'Belum ada produk dalam senarai. Rujuk katalog untuk mula pilih.',
    'cart.empty.button': 'Lihat katalog',
    'cart.item.remove': 'Buang',
    'cart.item.quantity': 'Kuantiti',
    'cart.subtotal': 'Anggaran subtotal',
    'cart.delivery': 'Anggaran logistik',
    'cart.total': 'Jumlah anggaran',
    'cart.checkout': 'Hantar permohonan sebut harga',
    'cart.continue': 'Teruskan pilih',
    'cart.delivery.note': 'Kos penghantaran bergantung kepada jumlah dan destinasi. Anggaran tepat diberi dalam sebut harga rasmi.',
    'cart.update': 'Kemaskini',
    'cart.clear': 'Kosongkan senarai',

    // Packages
    'packages.hero.title': 'Pakej mercun dipilih pakar',
    'packages.hero.subtitle': 'Pilih pakej sedia ada atau tempah pertunjukan khas ikut venue dan bajet.',
    'packages.wedding.title': 'Pakej kahwin',
    'packages.wedding.description': 'Entrance sparkler, fountain kek, dan finale romantik untuk resepsi indoor atau outdoor.',
    'packages.wedding.price': 'Dari RM299',
    'packages.raya.title': 'Pakej rumah terbuka',
    'packages.raya.description': 'Gabungan mesra keluarga dengan kawalan bunyi serta papan tanda keselamatan.',
    'packages.raya.price': 'Dari RM199',
    'packages.birthday.title': 'Pakej hari jadi / private party',
    'packages.birthday.description': 'Sparkler tangan, fountain rendah, dan surprise burst untuk laman rumah atau venue butik.',
    'packages.birthday.price': 'Dari RM149',
    'packages.newyear.title': 'Pakej countdown',
    'packages.newyear.description': 'Cake impak tinggi, finale bertema dan pilihan sync muzik untuk acara korporat atau awam.',
    'packages.newyear.price': 'Dari RM399',
    'packages.custom.title': 'Tempah rancangan khas',
    'packages.custom.description': 'Kongsikan konsep anda dan kami bina turutan show berlesen, crew serta dokumen permit.',
    'packages.custom.button': 'Minta pelan custom',
    'packages.whatsIncluded': 'Dalam pakej',
    'packages.orderNow': 'Mohon sebut harga',

    // Testimonials
    'testimonials.hero.title': 'Klien yang yakin dengan BMFireworks',
    'testimonials.hero.subtitle': 'Event planner, resort dan pasukan korporat berkongsi pengalaman mereka dengan crew kami.',
    'testimonials.review1.name': 'Azlan • Event Planner (KL)',
    'testimonials.review1.text': '“Bearboom × BMFireworks urus permit, rehearsal dan finale tepat masa. Klien puji proses yang sangat profesional.”',
    'testimonials.review1.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review2.name': 'Melissa • Pengurus Resort (Langkawi)',
    'testimonials.review2.text': '“Show pantai custom dengan briefing keselamatan jelas dan crew standby. Zero insiden, semua tetamu teruja.”',
    'testimonials.review2.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review3.name': 'Iqbal • Wedding Planner (Pulau Pinang)',
    'testimonials.review3.text': '“Daripada sparkler tetamu hingga finale meletup, semuanya dihantar on time dengan kelulusan lengkap.”',
    'testimonials.review3.rating': '⭐⭐⭐⭐⭐',
    'testimonials.review4.name': 'Samantha • Lead Aktivasi Jenama',
    'testimonials.review4.text': '“Komunikasi laju, laporan risiko terperinci, dan file show mudah untuk audit dalaman kami. Akan bekerjasama lagi.”',
    'testimonials.review4.rating': '⭐⭐⭐⭐⭐',
    'testimonials.cta.title': 'Jom rancang pertunjukan seterusnya',
    'testimonials.cta.button': 'Tempah sesi konsultasi',

    // Footer
    'footer.description': 'Bearboom × BMFireworks ialah rakan mercun berlesen untuk bekalan, nasihat permit dan crew acara.',
    'footer.quickLinks': 'Pautan pantas',
    'footer.links.catalogue': 'Katalog produk',
    'footer.links.packages': 'Pakej acara',
    'footer.links.permit': 'Panduan permit',
    'footer.links.safety': 'Panduan keselamatan',
    'footer.links.testimonials': 'Testimoni',
    'footer.links.contact': 'Hubungi kami',
    'footer.categories': 'Kategori popular',
    'footer.support': 'Sokongan pelanggan',
    'footer.whatsapp': 'WhatsApp',
    'footer.email': 'Emel', 
    'footer.contact.title': 'Hubungi',
    'footer.contact.phone': '📱 WhatsApp: +60 13-734 0415',
    'footer.contact.email': '📧 Emel: hello@bmfirework.com',
    'footer.contact.hours': '🕒 Isnin–Sabtu: 9AM–6PM',
    'footer.contact.location': '📍 Kuala Lumpur, Malaysia',
    'footer.hours': 'Waktu operasi',
    'footer.hours.time': 'Isn–Jum 9pg–6ptg • Sab 9pg–2ptg',
    'footer.partnership': 'Bearboom × BMFireworks Partnership 🎆',
    'footer.legalNote': 'Operasi mematuhi garis panduan & permit mercun Malaysia.',
    'footer.legal': 'Info undang-undang',
    'footer.privacy': 'Dasar privasi',
    'footer.terms': 'Terma & syarat',
    'footer.license': 'Pembekal sah • Pematuhan SSM & PDRM',
    'footer.copyright': '© 2025 BMFireworks. Semua hak terpelihara.',

    // Common
    'whatsapp.text': '💬 Tekan sini untuk WhatsApp BMFireworks',
    'common.price': 'RM',
    'common.products': 'produk',
    'common.loading': 'Memuatkan...',
    'common.error': 'Alamak! Ada masalah. Cuba lagi.',
    'common.success': 'Berjaya! Terima kasih!',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};